import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        int count;
        int gen;
        int ngen;
        int countT = 0;
        int counttwo = 0;
        int countthree = 0;
        int countfour = 0;

        // Set a fixed seed to make random numbers predictable
        Random generetor = new Random(seed);

        for (int rep = T; rep > 0; rep--) {
            count = 1;
            gen = generetor.nextInt(2);
            ngen = gen;

            while (gen == ngen) {
                ngen = generetor.nextInt(2);
                count++;
            }

            if (count == 2) {
                counttwo++;
            } else if (count == 3) {
                countthree++;
            } else {
                countfour++;
            }
            countT += count;
           
        } 
        double avg = ((double) countT) / T;
        System.out.println("Average: " + avg + " children to get at least one of each gender.");
        System.out.println("number of families with 2 children: " + counttwo);
        System.out.println("number of families with 3 children:  " + countthree);
        System.out.println("number of families with 4 or more children:  " + countfour);

        int common = Math.max(Math.max(counttwo, countthree), countfour);
        String commonstr;

        if (common == counttwo) {
            commonstr = "2";
        } else if (common == countthree) {
            commonstr = "3";
        } else {
            commonstr = "4 or more";
        }
        System.out.println("The most common number of children is " + commonstr);
    }
}